### ISSUE TITLE
angularlogos.com should link to orginal websites

### ISSUE THREAD

**Issue by JohannesHoppe** [maartentibau/angular-logos#47]
I think in the current state the logos are lacking any context. It would add a lot of value if all those great websites behind the logos could be made recognisable.

Proposal for a quick success:
The websites will be linked by filename convention:

* `ng-heidelberg.svg` no link at all
* `ng-heidelberg___angular-heidelberg.de.svg` links to https://angular-heidelberg.de

FYI @fmalcher

**Comment by fmalcher** [comment]
+1 for the general idea! Adding metadata to the logos is very sensible.
However, I'd not put the URL into the filename but rather provide rich metadata information.
This could add tags/category, display name, website URL and source (optional).

For now the website is a more accessible version of the repo, so we're improving ;-)

**Comment by fmalcher** [comment]
This could also be done with a *supplementary* JSON file. If an entry exists in the JSON, it will be used – if not, the logo will be displayed anyway. So the source of the logo list is always the file list and we can enrich the list by adding JSON entries over time.

**Comment by JohannesHoppe** [comment]
We could use this as a starting point:
https://github.com/UltimateAngular/angularconferences.github.io/blob/2db206bf9511be437813f3e8f679570d61a7d360/_data/2019.json#L453

But I found the huge JSON file very annoying. Then rather the following set:
* `ng-heidelberg.svg`
* `ng-heidelberg.json`

That way merging should always be as easy as pie, too.

**Comment by fmalcher** [comment]
Since we fetch the files directly from the repo, I don't think it's a good idea to make 100 HTTP calls for 100 single JSON files...

**Comment by JohannesHoppe** [comment]
Fair point!

**Comment by maartentibau** [comment]
My first idea would be to just create a global JSON file. I know it is not ideal but since we're not adding logos every day I think we can manage just within the PR's.

So a PR would require to add an `.svg` logo add some extra info with that PR. My suggestion is to create some kind of default template for PR's.

The extra questions would be:
- name: required
- website: optional
- license: optional
- creator: optional
- description: optional

So the task to keep the JSON up to date is up to owner and collaborators of the repo, I would not leave this into the hands of the contributors personally, since it might even hold back certain people maybe.

The structure of the JSON file would be

```json
"angular.svg": {
  "name": "Angular",
  "website": "https://angular.io",
  "license": "MIT",
  "creator": "Google",
  "description": "Angular logo"
}
```

A good things is, we can easily provide a fallback on the website, if no key is found in the JSON we just show the file name as the name of the logo (as we already do right now).

**Comment by fmalcher** [comment]
I thought of it the same way, very good. I think it's important to keep the JSON entry optional so the logo will be displayed anyway, even without an entry.

**Comment by fmalcher** [comment]
PR with first version: https://github.com/maartentibau/angularlogoscom/pull/16

**Comment by fmalcher** [comment]
The first step is done 😎now we need metadata. much wow
